/** 页面中文文案（可直接编辑，文件请保存为 UTF-8） */
export const STR = {
  pageTitle: "八数码问题 — A* 与 BFS 对比实验",
  mainTitle: "八数码问题求解实验",
  subtitle: "BFS（h=0）· A*（不在位数）· A*（曼哈顿距离）",
  inputSection: "初始状态设置",
  inputHint: "在左侧 9 格中输入 0～8，每个数字恰好出现一次（0 表示空格）；右侧为固定推理目标。",
  startBlockTitle: "初始状态",
  startBlockNote: "可手动修改或随机生成",
  btnDefault: "恢复默认样例",
  btnRandom: "随机可解初态",
  btnSolve: "开始求解",
  goalTitle: "目标状态（固定）",
  goalCaption: "目标结果，与Matlab类似",
  colBfs: "BFS",
  colSubBfs: "h(n) = 0",
  resultSection: "求解结果",
  colAlgo: "算法",
  colHeuristic: "估价函数 h(n)",
  colSteps: "解步数",
  colExpanded: "扩展节点数",
  colGenerated: "生成节点数",
  colTime: "耗时 (ms)",
  chartExpanded: "扩展节点数对比",
  chartGenerated: "生成节点数对比",
  demoSection: "移动过程演示",
  syncPlay: "三算法同步播放",
  demoHint: "求解成功后，三列将显示当前步的 3×3 盘面",
  btnPrev: "上一步",
  btnNext: "下一步",
  btnPlay: "播放",
  colMisplaced: "A* · 不在位数",
  colManhattan: "A* · 曼哈顿",
  hMisplaced: "h(n) = 错位数",
  hManhattan: "h(n) = 曼哈顿距离",
  reportToggle: "实验说明 · A* 框图 · 启发式分析",
  footer: "人工智能 · 八数码问题",
  dash: "—",
  cellLabel: "格子",
  stepFmt: "第 {i} / {max} 步",
  dotTitle: "第 {i} 步",
  dotAria: "跳转到第 {i} 步",
  needNine: "需要恰好 9 个数字。",
  cellInt: "每个格子必须是 0～8 的整数。",
  cellDup: "数字 {v} 重复出现，0～8 各只能出现一次。",
  needAll: "必须包含 0～8 全部九个数字。",
  goalErr: "目标状态配置错误。",
  unsolvable: "当前初始状态无法到达目标状态（逆序对奇偶性与目标不一致）。请修改初态或点击「随机可解初态」。",
  searchFail: "搜索未找到解（请检查输入或实现）。",
  demoHintDone: "三列同步显示当前步；最优步数应相同，具体走法可能不同。",
  chartExpandedLabel: "扩展节点数",
  chartGeneratedLabel: "生成节点数",
  misplaced: "不在位数",
  manhattan: "曼哈顿距离",
  algoMisplaced: "A* · 不在位数",
  algoManhattan: "A* · 曼哈顿",
  reportH2Flow: "A* 算法求解框图",
  reportFlow: "开始\n  ↓\n将初始状态放入 Open 表，generated ← 1\n  ↓\nOpen 为空？ ——是——→ 无解，结束\n  ↓否\n取出 f(n)=g(n)+h(n) 最小的节点 n，expanded ← expanded+1\n  ↓\nn 是目标？ ——是——→ 回溯路径，输出统计，结束\n  ↓否\n将 n 加入 Closed\n  ↓\n扩展 n 的每个合法后继 s\n  ↓\ns 在 Closed？ ——是——→ 跳过\n  ↓否\ns 不在 Open 或 经 n 到 s 的 g 更小？\n  ↓是\n将 s 加入/更新 Open，generated ← generated+1\n  ↓\n返回「取出 f 最小节点」",
  reportH2Heuristic: "两种估价函数",
  reportH2Analysis: "启发式搜索区别",
  reportAnalysis: "在相同初态与目标下，三种算法应得到相同的最短步数（可采纳启发式保证 A* 最优）。差异主要体现在扩展节点数与生成节点数： h 越接近真实代价，搜索越有方向性。曼哈顿距离一般优于不在位数；BFS 无启发信息，适合作为对照基线。",
  heuristicItems: [
    "不在位数：数字 1～8 中，不在目标位置上的个数。",
    "曼哈顿距离：每个数字到目标位置的 |Δ行|+|Δ列| 之和（不含空格）。",
    "BFS：令 h(n)=0，按层广度优先，保证最短步数但搜索量通常最大。",
  ],
};
